import RiemannDynamics.Teichmuller.Compactness.Mumford

/-!
# Covolume bounds and limit cocompactness for Fuchsian groups

A cocompact subgroup of `SL(2, ℝ)` acting on the upper half plane admits a compact covering
set (`exists_compact_covering`), so it satisfies the area-bound hypothesis of the Mumford
subconvergence theorems for some finite bound (`hasAreaBound_of_cocompact`), as does the
Fuchsian group of any
Teichmüller representative over a cocompact base (`TeichRep.exists_hasAreaBound`).

For a sequence of trace-gapped groups with uniformly dense orbits and convergent
ball-generator tuples, orbit density transports to the group generated by the limit tuple
(`limit_orbit_dense`): each point of a chain from the basepoint to a target is approximated
in the `n`-th orbit, the increments are ball generators, and one fixed word shape passes to
the limit along a pigeonhole subsequence. Density yields cocompactness of the limit group
(`cocompact_of_orbit_dense`, `limit_group_cocompact`) together with an explicit covering
volume bound (`hasAreaBound_limit_group`). The self-contained subconvergence form
`mumford_subconvergence_thick` produces the ball-generator tuples internally, so the
displacement bound of `mumford_generator_subconvergence` is discharged rather than assumed.
-/

open MeasureTheory
open scoped ENNReal

namespace RiemannDynamics

/-! ## Compact covering sets and the area bound -/

/-- A cocompact action on the upper half plane admits a compact set meeting every orbit. -/
theorem exists_compact_covering (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ))
    (hcc : CompactSpace (Quotient (MulAction.orbitRel Γ UpperHalfPlane))) :
    ∃ K : Set UpperHalfPlane, IsCompact K ∧ ∀ τ : UpperHalfPlane, ∃ γ : Γ, γ • τ ∈ K := by
  haveI : ContinuousConstSMul (↥Γ) UpperHalfPlane :=
    ⟨fun c => (isometry_smul UpperHalfPlane
      (c : Matrix.SpecialLinearGroup (Fin 2) ℝ)).continuous⟩
  have hq : IsOpenQuotientMap (Quotient.mk (MulAction.orbitRel Γ UpperHalfPlane)) :=
    MulAction.isOpenQuotientMap_quotientMk
  have hcover : (Set.univ : Set (Quotient (MulAction.orbitRel Γ UpperHalfPlane))) ⊆
      ⋃ τ : UpperHalfPlane,
        Quotient.mk (MulAction.orbitRel Γ UpperHalfPlane) '' Metric.ball τ 1 := by
    rintro x -
    obtain ⟨τ, rfl⟩ := hq.surjective x
    exact Set.mem_iUnion.mpr ⟨τ, Set.mem_image_of_mem _ (Metric.mem_ball_self one_pos)⟩
  obtain ⟨t, ht⟩ := isCompact_univ.elim_finite_subcover
    (fun τ : UpperHalfPlane =>
      Quotient.mk (MulAction.orbitRel Γ UpperHalfPlane) '' Metric.ball τ 1)
    (fun τ => hq.isOpenMap _ Metric.isOpen_ball) hcover
  refine ⟨⋃ i ∈ t, Metric.closedBall i 1,
    t.finite_toSet.isCompact_biUnion fun i _ => isCompact_closedBall i 1, fun τ => ?_⟩
  have hmem := ht (Set.mem_univ (Quotient.mk (MulAction.orbitRel Γ UpperHalfPlane) τ))
  obtain ⟨i, hi, y, hy, hqy⟩ := Set.mem_iUnion₂.mp hmem
  obtain ⟨γ, hγ⟩ := MulAction.mem_orbit_iff.mp
    (MulAction.orbitRel_apply.mp (Quotient.exact hqy))
  exact ⟨γ, hγ ▸ Set.mem_biUnion hi (Metric.ball_subset_closedBall hy)⟩

/-- Cocompact Fuchsian groups satisfy the area-bound hypothesis for some finite bound: the
volume of a compact covering set is finite. -/
theorem hasAreaBound_of_cocompact (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ))
    (hcc : CompactSpace (Quotient (MulAction.orbitRel Γ UpperHalfPlane))) :
    ∃ A : ℝ≥0∞, A ≠ ⊤ ∧ HasAreaBound Γ A := by
  obtain ⟨K, hK, hcov⟩ := exists_compact_covering Γ hcc
  exact ⟨volume K, hK.measure_lt_top.ne,
    K, hK.isClosed.measurableSet, Filter.Eventually.of_forall hcov, le_rfl⟩

/-- Over a cocompact base, the Fuchsian group of every Teichmüller representative satisfies
the area-bound hypothesis for some finite bound. -/
theorem TeichRep.exists_hasAreaBound {Γ₀ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ)}
    (hcc : CompactSpace (Quotient (MulAction.orbitRel Γ₀ UpperHalfPlane)))
    (x : TeichRep Γ₀) : ∃ A : ℝ≥0∞, A ≠ ⊤ ∧ HasAreaBound x.group A :=
  hasAreaBound_of_cocompact x.group (x.group_cocompact hcc)

/-! ## Uniform ball-generator tuples -/

/-- A packing count for the displacement ball of a trace-gapped Fuchsian group: twice the
number of disjoint `ε/2`-balls fitting in the `(R + ε/2)`-ball about `i`, plus padding. -/
noncomputable def ballGensCard (ε R : ℝ) : ℕ :=
  2 * (⌊(volume (Metric.ball UpperHalfPlane.I (R + ε / 2))
    / upperBallVolume (ε / 2)).toReal⌋₊ + 1)

/-- The displacement ball of a trace-gapped Fuchsian group is finite, of cardinality bounded
by the packing count of the ball; a tuple enumerating it (with repetition) exists in any
uniform index size. -/
theorem exists_ball_gens_tuple {Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ)}
    (hΓ : IsFuchsianGroup Γ) {ε R : ℝ} (hε : 0 < ε) (hR : 0 ≤ R)
    (hgap : ∀ γ ∈ Γ, actsNontrivially γ → ε ≤ translationLength γ) :
    ∃ (m : ℕ) (gens : Fin m → Matrix.SpecialLinearGroup (Fin 2) ℝ),
      m = ballGensCard ε R ∧ (∀ i, gens i ∈ Γ) ∧
      (∀ i, dist UpperHalfPlane.I (gens i • UpperHalfPlane.I) ≤ R) ∧
      (∀ γ ∈ Γ, dist UpperHalfPlane.I (γ • UpperHalfPlane.I) ≤ R → ∃ i, gens i = γ) := by
  classical
  haveI hPD : ProperlyDiscontinuousSMul (↥Γ) UpperHalfPlane := hΓ
  -- the displacement ball is a finite set
  have hfin1 : {γ : ↥Γ | ((fun x => γ • x) '' {UpperHalfPlane.I} ∩
      Metric.closedBall UpperHalfPlane.I R).Nonempty}.Finite :=
    ProperlyDiscontinuousSMul.finite_disjoint_inter_image isCompact_singleton
      (isCompact_closedBall _ _)
  have hBfin : {γ : Matrix.SpecialLinearGroup (Fin 2) ℝ |
      γ ∈ Γ ∧ dist UpperHalfPlane.I (γ • UpperHalfPlane.I) ≤ R}.Finite := by
    refine (hfin1.image (fun γ : ↥Γ => (γ : Matrix.SpecialLinearGroup (Fin 2) ℝ))).subset ?_
    rintro γ ⟨hγΓ, hγd⟩
    refine ⟨⟨γ, hγΓ⟩, ⟨γ • UpperHalfPlane.I, ⟨UpperHalfPlane.I, rfl, rfl⟩, ?_⟩, rfl⟩
    rw [Metric.mem_closedBall, dist_comm]
    exact hγd
  obtain ⟨Bfin, hBfindef⟩ : ∃ Bfin : Finset (Matrix.SpecialLinearGroup (Fin 2) ℝ),
      Bfin = hBfin.toFinset := ⟨_, rfl⟩
  have hBmem : ∀ γ : Matrix.SpecialLinearGroup (Fin 2) ℝ, γ ∈ Bfin ↔
      γ ∈ Γ ∧ dist UpperHalfPlane.I (γ • UpperHalfPlane.I) ≤ R := by
    intro γ
    rw [hBfindef, hBfin.mem_toFinset]
    exact Iff.rfl
  -- distinct orbit points of ball elements are `ε`-separated
  have hsep : ∀ γ ∈ Bfin, ∀ δ ∈ Bfin, γ • UpperHalfPlane.I ≠ δ • UpperHalfPlane.I →
      ε ≤ dist (γ • UpperHalfPlane.I) (δ • UpperHalfPlane.I) := by
    intro γ hγ δ hδ hne
    have hnt : actsNontrivially (γ⁻¹ * δ) := by
      refine ⟨UpperHalfPlane.I, fun h0 => hne ?_⟩
      have h1 : γ • (γ⁻¹ * δ) • UpperHalfPlane.I = γ • UpperHalfPlane.I := by rw [h0]
      rwa [← mul_smul, mul_inv_cancel_left, eq_comm] at h1
    have hlen : ε ≤ translationLength (γ⁻¹ * δ) :=
      hgap _ (mul_mem (inv_mem ((hBmem γ).mp hγ).1) ((hBmem δ).mp hδ).1) hnt
    have hhyp := (translationLength_pos_iff (γ⁻¹ * δ)).mp (lt_of_lt_of_le hε hlen)
    have h2 := translationLength_le_dist_smul (γ⁻¹ * δ) hhyp UpperHalfPlane.I
    have h3 : dist UpperHalfPlane.I ((γ⁻¹ * δ) • UpperHalfPlane.I)
        = dist (γ • UpperHalfPlane.I) (δ • UpperHalfPlane.I) := by
      rw [mul_smul, ← dist_smul γ UpperHalfPlane.I (γ⁻¹ • δ • UpperHalfPlane.I),
        smul_inv_smul]
    rw [h3] at h2
    linarith
  obtain ⟨Pimg, hPimgdef⟩ : ∃ Pimg : Finset UpperHalfPlane,
      Pimg = Bfin.image (fun γ => γ • UpperHalfPlane.I) := ⟨_, rfl⟩
  -- each fiber of `γ ↦ γ • i` over the ball has at most two elements
  have hfiber : ∀ p ∈ Pimg, {γ ∈ Bfin | γ • UpperHalfPlane.I = p}.card ≤ 2 := by
    intro p hp
    rcases Finset.eq_empty_or_nonempty {γ ∈ Bfin | γ • UpperHalfPlane.I = p} with h | h
    · rw [h, Finset.card_empty]
      norm_num
    · obtain ⟨γ₀, hγ₀⟩ := h
      have hγ₀f := Finset.mem_filter.mp hγ₀
      have hcoe : ∀ δ ∈ {γ ∈ Bfin | γ • UpperHalfPlane.I = p},
          ((δ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ)
            = ((γ₀ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ) ∨
          ((δ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ)
            = -((γ₀ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ) := by
        intro δ hδ
        have hδf := Finset.mem_filter.mp hδ
        have hfix : (γ₀⁻¹ * δ) • UpperHalfPlane.I = UpperHalfPlane.I := by
          rw [mul_smul, hδf.2, ← hγ₀f.2, inv_smul_smul]
        have htriv : ∀ τ' : UpperHalfPlane, (γ₀⁻¹ * δ) • τ' = τ' := by
          by_cases hnt : actsNontrivially (γ₀⁻¹ * δ)
          · exfalso
            have hlen := hgap _
              (mul_mem (inv_mem ((hBmem γ₀).mp hγ₀f.1).1) ((hBmem δ).mp hδf.1).1) hnt
            have hhyp := (translationLength_pos_iff (γ₀⁻¹ * δ)).mp (lt_of_lt_of_le hε hlen)
            have h2 := translationLength_le_dist_smul (γ₀⁻¹ * δ) hhyp UpperHalfPlane.I
            rw [hfix, dist_self] at h2
            linarith
          · intro τ'
            by_contra hne'
            exact hnt ⟨τ', hne'⟩
        have hgrp : γ₀ * (γ₀⁻¹ * δ) = δ := mul_inv_cancel_left γ₀ δ
        have hm : ((γ₀ * (γ₀⁻¹ * δ) : Matrix.SpecialLinearGroup (Fin 2) ℝ) :
            Matrix (Fin 2) (Fin 2) ℝ)
            = ((δ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ) := by
          rw [hgrp]
        rw [Matrix.SpecialLinearGroup.coe_mul] at hm
        rcases (smul_id_iff_pm_one _).mp htriv with h1 | h1
        · left
          rw [h1, mul_one] at hm
          exact hm.symm
        · right
          rw [h1, mul_neg_one] at hm
          exact hm.symm
      have hcard2 : {γ ∈ Bfin | γ • UpperHalfPlane.I = p}.card
          ≤ ({((γ₀ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ),
              -((γ₀ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ)} :
              Finset (Matrix (Fin 2) (Fin 2) ℝ)).card := by
        refine Finset.card_le_card_of_injOn
          (fun δ => ((δ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ))
          (fun δ hδ => ?_) (fun a _ b _ hab => Subtype.coe_injective hab)
        rcases hcoe δ (Finset.mem_coe.mp hδ) with h | h
        · exact Finset.mem_coe.mpr (Finset.mem_insert.mpr (Or.inl h))
        · exact Finset.mem_coe.mpr
            (Finset.mem_insert.mpr (Or.inr (Finset.mem_singleton.mpr h)))
      refine hcard2.trans ((Finset.card_insert_le _ _).trans ?_)
      rw [Finset.card_singleton]
  -- disjoint `ε/2`-balls at the orbit points pack the `(R + ε/2)`-ball about `i`
  have hdisj : (↑Pimg : Set UpperHalfPlane).PairwiseDisjoint
      (fun p => Metric.ball p (ε / 2)) := by
    intro x hx y hy hxy
    obtain ⟨γ, hγ, rfl⟩ := Finset.mem_image.mp (hPimgdef ▸ Finset.mem_coe.mp hx)
    obtain ⟨δ, hδ, rfl⟩ := Finset.mem_image.mp (hPimgdef ▸ Finset.mem_coe.mp hy)
    exact Metric.ball_disjoint_ball (by linarith [hsep γ hγ δ hδ hxy])
  have hsub2 : (⋃ q ∈ Pimg, Metric.ball q (ε / 2))
      ⊆ Metric.ball UpperHalfPlane.I (R + ε / 2) := by
    intro x hx
    obtain ⟨q, hq, hxq⟩ := Set.mem_iUnion₂.mp hx
    obtain ⟨γ, hγ, rfl⟩ := Finset.mem_image.mp (hPimgdef ▸ hq)
    rw [Metric.mem_ball] at hxq ⊢
    have h1 : dist x UpperHalfPlane.I ≤ dist x (γ • UpperHalfPlane.I)
        + dist (γ • UpperHalfPlane.I) UpperHalfPlane.I := dist_triangle _ _ _
    rw [dist_comm (γ • UpperHalfPlane.I) UpperHalfPlane.I] at h1
    linarith [((hBmem γ).mp hγ).2]
  have hvol : (Pimg.card : ℝ≥0∞) * upperBallVolume (ε / 2)
      ≤ volume (Metric.ball UpperHalfPlane.I (R + ε / 2)) := by
    have h1 : volume (⋃ q ∈ Pimg, Metric.ball q (ε / 2))
        = ∑ q ∈ Pimg, volume (Metric.ball q (ε / 2)) :=
      measure_biUnion_finset hdisj (fun q _ => measurableSet_ball)
    have h2 : ∑ q ∈ Pimg, volume (Metric.ball q (ε / 2))
        = Pimg.card • upperBallVolume (ε / 2) := by
      rw [Finset.sum_congr rfl (fun q _ => volume_ball_eq_upperBallVolume q (ε / 2)),
        Finset.sum_const]
    calc (Pimg.card : ℝ≥0∞) * upperBallVolume (ε / 2)
        = Pimg.card • upperBallVolume (ε / 2) := (nsmul_eq_mul _ _).symm
      _ = volume (⋃ q ∈ Pimg, Metric.ball q (ε / 2)) := by rw [h1, h2]
      _ ≤ volume (Metric.ball UpperHalfPlane.I (R + ε / 2)) := measure_mono hsub2
  -- the packing count bounds the number of orbit points
  have hv0 : upperBallVolume (ε / 2) ≠ 0 := (upperBallVolume_pos (by linarith)).ne'
  have hvtop : upperBallVolume (ε / 2) ≠ ⊤ := by
    have h1 : upperBallVolume (ε / 2) ≤ volume (Metric.closedBall UpperHalfPlane.I (ε / 2)) := by
      rw [← volume_ball_eq_upperBallVolume UpperHalfPlane.I (ε / 2)]
      exact measure_mono Metric.ball_subset_closedBall
    exact (lt_of_le_of_lt h1 (isCompact_closedBall _ _).measure_lt_top).ne
  have hVtop : volume (Metric.ball UpperHalfPlane.I (R + ε / 2)) ≠ ⊤ :=
    (lt_of_le_of_lt (measure_mono Metric.ball_subset_closedBall)
      (isCompact_closedBall _ _).measure_lt_top).ne
  have hcardP : Pimg.card ≤ ⌊(volume (Metric.ball UpperHalfPlane.I (R + ε / 2))
      / upperBallVolume (ε / 2)).toReal⌋₊ := by
    have hdiv : (Pimg.card : ℝ≥0∞) ≤ volume (Metric.ball UpperHalfPlane.I (R + ε / 2))
        / upperBallVolume (ε / 2) :=
      (ENNReal.le_div_iff_mul_le (Or.inl hv0) (Or.inl hvtop)).mpr hvol
    have hdivtop : volume (Metric.ball UpperHalfPlane.I (R + ε / 2))
        / upperBallVolume (ε / 2) ≠ ⊤ := by
      rw [Ne, ENNReal.div_eq_top]
      rintro (⟨-, h0⟩ | ⟨ht, -⟩)
      · exact hv0 h0
      · exact hVtop ht
    refine Nat.le_floor ?_
    rw [← ENNReal.toReal_natCast Pimg.card]
    exact (ENNReal.toReal_le_toReal (ENNReal.natCast_ne_top _) hdivtop).mpr hdiv
  -- the ball cardinality is bounded by the packing count
  have hcardB : Bfin.card ≤ ballGensCard ε R := by
    have h1 : Bfin.card ≤ 2 * Pimg.card := by
      rw [hPimgdef]
      exact Finset.card_le_mul_card_image Bfin 2 (hPimgdef ▸ hfiber)
    have h2 : ballGensCard ε R
        = 2 * (⌊(volume (Metric.ball UpperHalfPlane.I (R + ε / 2))
          / upperBallVolume (ε / 2)).toReal⌋₊ + 1) := rfl
    omega
  -- enumerate the ball with repetition-padding by the identity
  have hlenle : Bfin.toList.length ≤ ballGensCard ε R := by
    rw [Finset.length_toList]
    exact hcardB
  refine ⟨ballGensCard ε R, fun i => if h : (i : ℕ) < Bfin.toList.length
      then Bfin.toList[(i : ℕ)]'h else 1, rfl, ?_, ?_, ?_⟩
  · intro i
    by_cases h : (i : ℕ) < Bfin.toList.length
    · simp only [dif_pos h]
      exact ((hBmem _).mp (Finset.mem_toList.mp (List.getElem_mem h))).1
    · simp only [dif_neg h]
      exact one_mem Γ
  · intro i
    by_cases h : (i : ℕ) < Bfin.toList.length
    · simp only [dif_pos h]
      exact ((hBmem _).mp (Finset.mem_toList.mp (List.getElem_mem h))).2
    · simp only [dif_neg h]
      rw [one_smul, dist_self]
      exact hR
  · intro γ hγΓ hγd
    have hγB : γ ∈ Bfin := (hBmem γ).mpr ⟨hγΓ, hγd⟩
    obtain ⟨j, hj, hjeq⟩ := List.mem_iff_getElem.mp (Finset.mem_toList.mpr hγB)
    refine ⟨⟨j, lt_of_lt_of_le hj hlenle⟩, ?_⟩
    change (if h : j < Bfin.toList.length then Bfin.toList[j]'h else 1) = γ
    rw [dif_pos hj]
    exact hjeq

/-! ## Group-variable continuity of the action -/

/-- The action of `SL(2, ℝ)` on the upper half plane is continuous in the group variable:
entrywise convergence of matrices gives convergence of the Möbius values. -/
theorem tendsto_smul_of_tendsto {u : ℕ → Matrix.SpecialLinearGroup (Fin 2) ℝ}
    {ρ : Matrix.SpecialLinearGroup (Fin 2) ℝ}
    (hu : Filter.Tendsto u Filter.atTop (nhds ρ)) (τ : UpperHalfPlane) :
    Filter.Tendsto (fun n => u n • τ) Filter.atTop (nhds (ρ • τ)) := by
  -- entrywise convergence of the matrices
  have hmat : Filter.Tendsto (fun n => ((u n : Matrix.SpecialLinearGroup (Fin 2) ℝ) :
      Matrix (Fin 2) (Fin 2) ℝ)) Filter.atTop
      (nhds ((ρ : Matrix.SpecialLinearGroup (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ)) :=
    tendsto_subtype_rng.mp hu
  have hentry : ∀ k l : Fin 2, Filter.Tendsto (fun n => ((u n) k l : ℂ)) Filter.atTop
      (nhds ((ρ k l : ℝ) : ℂ)) := by
    intro k l
    exact (Complex.continuous_ofReal.tendsto _).comp
      (tendsto_pi_nhds.mp (tendsto_pi_nhds.mp hmat k) l)
  -- convergence of numerator and denominator
  have hnum : Filter.Tendsto (fun n => ((u n) 0 0 : ℂ) * (τ : ℂ) + ((u n) 0 1 : ℂ))
      Filter.atTop (nhds ((ρ 0 0 : ℂ) * (τ : ℂ) + (ρ 0 1 : ℂ))) :=
    ((hentry 0 0).mul tendsto_const_nhds).add (hentry 0 1)
  have hden : Filter.Tendsto (fun n => moebiusDenom (u n) (τ : ℂ))
      Filter.atTop (nhds (moebiusDenom ρ (τ : ℂ))) := by
    simp only [moebiusDenom]
    exact ((hentry 1 0).mul tendsto_const_nhds).add (hentry 1 1)
  have hden_ne : moebiusDenom ρ (τ : ℂ) ≠ 0 :=
    moebiusDenom_ne_zero_of_im_ne_zero ρ
      (by rw [UpperHalfPlane.coe_im]; exact τ.im_pos.ne')
  -- convergence of the Möbius values in the plane
  have hdiv : Filter.Tendsto (fun n => moebiusMap (u n) (τ : ℂ)) Filter.atTop
      (nhds (moebiusMap ρ (τ : ℂ))) := by
    simp only [moebiusMap]
    exact hnum.div hden hden_ne
  -- pull back through the coercion
  rw [UpperHalfPlane.isOpenEmbedding_coe.toIsEmbedding.tendsto_nhds_iff]
  have hco : (UpperHalfPlane.coe ∘ fun n => u n • τ)
      = fun n => moebiusMap (u n) (τ : ℂ) :=
    funext fun n => coe_smul_eq_moebiusMap (u n) τ
  rw [hco, coe_smul_eq_moebiusMap]
  exact hdiv

/-! ## Density transport to the limit group -/

/-- Orbit density passes from a convergent sequence of trace-gapped groups to the group
generated by the limit tuple: chain a path from `i` to `σ`, approximate each chain point by
the `n`-th orbit, write the increments as ball generators, and pass one fixed word shape to
the limit along a pigeonhole subsequence. -/
theorem limit_orbit_dense {ι : Type} [Finite ι]
    (Γ : ℕ → Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ))
    {D : ℝ} (hD : 0 ≤ D)
    (hdense : ∀ n σ, Metric.infDist σ (MulAction.orbit (Γ n) UpperHalfPlane.I) ≤ D)
    (gens : ℕ → ι → Matrix.SpecialLinearGroup (Fin 2) ℝ)
    (hmem : ∀ n i, gens n i ∈ Γ n)
    (hball : ∀ n, ∀ γ ∈ Γ n, dist UpperHalfPlane.I (γ • UpperHalfPlane.I) ≤ 2 * D + 1 →
      ∃ i, gens n i = γ)
    (ρ : ι → Matrix.SpecialLinearGroup (Fin 2) ℝ)
    (hlim : ∀ i, Filter.Tendsto (fun n => gens n i) Filter.atTop (nhds (ρ i))) :
    ∀ σ : UpperHalfPlane, ∃ g ∈ Subgroup.closure (Set.range ρ),
      dist σ (g • UpperHalfPlane.I) ≤ D + 1 := by
  -- membership of the tuples is retained for statement-shape compatibility: the increments
  -- produced by `hball` carry their own membership proofs
  have _ := hmem
  intro σ
  -- a path from the basepoint to `σ` and a fine partition of it
  obtain ⟨p⟩ : Joined UpperHalfPlane.I σ := PathConnectedSpace.joined _ _
  have huc : UniformContinuousOn p.extend (Set.Icc 0 1) :=
    isCompact_Icc.uniformContinuousOn_of_continuous p.continuous_extend.continuousOn
  obtain ⟨dlt, hdlt0, hdimp⟩ := Metric.uniformContinuousOn_iff.mp huc (1 / 2) (by norm_num)
  obtain ⟨m', hm'⟩ := exists_nat_one_div_lt hdlt0
  obtain ⟨m, hmdef⟩ : ∃ m : ℕ, m = m' + 1 := ⟨_, rfl⟩
  have hm0 : (0 : ℝ) < (m : ℝ) := by
    rw [hmdef]
    positivity
  have hstep : (1 : ℝ) / (m : ℝ) < dlt := by
    rw [hmdef]
    push_cast
    exact hm'
  have hmem01 : ∀ j : ℕ, j ≤ m → (j : ℝ) / (m : ℝ) ∈ Set.Icc (0 : ℝ) 1 := by
    intro j hj
    constructor
    · positivity
    · rw [div_le_one hm0]
      exact_mod_cast hj
  have hclose : ∀ j : ℕ, j + 1 ≤ m →
      dist (p.extend ((j : ℝ) / (m : ℝ))) (p.extend (((j + 1 : ℕ) : ℝ) / (m : ℝ)))
        < 1 / 2 := by
    intro j hj
    refine hdimp _ (hmem01 j (by omega)) _ (hmem01 (j + 1) hj) ?_
    rw [Real.dist_eq]
    push_cast
    have heq : (j : ℝ) / (m : ℝ) - ((j : ℝ) + 1) / (m : ℝ) = -(1 / (m : ℝ)) := by ring
    rw [heq, abs_neg, abs_of_pos (div_pos one_pos hm0)]
    exact hstep
  -- approximate each partition point in the `n`-th orbit; the zeroth choice is the identity
  have hpick : ∀ n j : ℕ, ∃ c : Matrix.SpecialLinearGroup (Fin 2) ℝ, c ∈ Γ n ∧
      dist (p.extend ((j : ℝ) / (m : ℝ))) (c • UpperHalfPlane.I) < D + 1 / 4 ∧
      (j = 0 → c = 1) := by
    intro n j
    rcases Nat.eq_zero_or_pos j with hj | hj
    · refine ⟨1, one_mem _, ?_, fun _ => rfl⟩
      subst hj
      rw [Nat.cast_zero, zero_div, Path.extend_zero, one_smul, dist_self]
      linarith
    · have h1 : Metric.infDist (p.extend ((j : ℝ) / (m : ℝ)))
          (MulAction.orbit (Γ n) UpperHalfPlane.I) < D + 1 / 4 :=
        lt_of_le_of_lt (hdense n _) (by linarith)
      have hne : (MulAction.orbit (Γ n) UpperHalfPlane.I).Nonempty :=
        ⟨UpperHalfPlane.I, MulAction.mem_orbit_self _⟩
      obtain ⟨y, hy, hxy⟩ := (Metric.infDist_lt_iff hne).mp h1
      obtain ⟨c, rfl⟩ := MulAction.mem_orbit_iff.mp hy
      exact ⟨(c : Matrix.SpecialLinearGroup (Fin 2) ℝ), c.2, hxy,
        fun h0 => absurd h0 (by omega)⟩
  choose b hbmem hbdist hbzero using hpick
  -- each increment is a ball generator
  have hinc : ∀ (n : ℕ) (j : Fin m), ∃ i : ι,
      gens n i = (b n (j : ℕ))⁻¹ * b n ((j : ℕ) + 1) := by
    intro n j
    refine hball n _ (mul_mem (inv_mem (hbmem n (j : ℕ))) (hbmem n ((j : ℕ) + 1))) ?_
    have h1 : dist UpperHalfPlane.I
        (((b n (j : ℕ))⁻¹ * b n ((j : ℕ) + 1)) • UpperHalfPlane.I)
        = dist (b n (j : ℕ) • UpperHalfPlane.I) (b n ((j : ℕ) + 1) • UpperHalfPlane.I) := by
      rw [mul_smul, ← dist_smul (b n (j : ℕ)) UpperHalfPlane.I
        ((b n (j : ℕ))⁻¹ • b n ((j : ℕ) + 1) • UpperHalfPlane.I), smul_inv_smul]
    rw [h1]
    have h2 := hbdist n (j : ℕ)
    have h3 := hbdist n ((j : ℕ) + 1)
    have h4 : dist (p.extend (((j : ℕ) : ℝ) / (m : ℝ)))
        (p.extend ((((j : ℕ) + 1 : ℕ) : ℝ) / (m : ℝ))) < 1 / 2 := hclose (j : ℕ) j.isLt
    have h5 := dist_triangle4 (b n (j : ℕ) • UpperHalfPlane.I)
      (p.extend (((j : ℕ) : ℝ) / (m : ℝ))) (p.extend ((((j : ℕ) + 1 : ℕ) : ℝ) / (m : ℝ)))
      (b n ((j : ℕ) + 1) • UpperHalfPlane.I)
    rw [dist_comm (b n (j : ℕ) • UpperHalfPlane.I)
      (p.extend (((j : ℕ) : ℝ) / (m : ℝ)))] at h5
    linarith
  choose idx hidx using hinc
  -- pigeonhole: one index tuple recurs infinitely often
  obtain ⟨t, ht⟩ := Finite.exists_infinite_fiber idx
  have hSinf : (idx ⁻¹' {t}).Infinite := Set.infinite_coe_iff.mp ht
  -- one fixed word shape converges to an element of the limit group
  have main : ∀ l : ℕ, l ≤ m → ∃ (g : Matrix.SpecialLinearGroup (Fin 2) ℝ)
      (w : ℕ → Matrix.SpecialLinearGroup (Fin 2) ℝ),
      g ∈ Subgroup.closure (Set.range ρ) ∧
      Filter.Tendsto w Filter.atTop (nhds g) ∧
      ∀ n ∈ idx ⁻¹' {t}, w n = b n l := by
    intro l
    induction l with
    | zero =>
      intro _
      exact ⟨1, fun _ => 1, one_mem _, tendsto_const_nhds,
        fun n _ => (hbzero n 0 rfl).symm⟩
    | succ l ih =>
      intro hl
      obtain ⟨g, w, hgmem, hw, hwS⟩ := ih (Nat.le_of_succ_le hl)
      refine ⟨g * ρ (t ⟨l, hl⟩), fun n => w n * gens n (t ⟨l, hl⟩),
        mul_mem hgmem (Subgroup.subset_closure ⟨t ⟨l, hl⟩, rfl⟩),
        hw.mul (hlim (t ⟨l, hl⟩)), ?_⟩
      intro n hn
      have hidxn : idx n ⟨l, hl⟩ = t ⟨l, hl⟩ := by
        rw [Set.mem_preimage, Set.mem_singleton_iff] at hn
        rw [hn]
      have hgens : gens n (t ⟨l, hl⟩) = (b n l)⁻¹ * b n (l + 1) := by
        rw [← hidxn]
        exact hidx n ⟨l, hl⟩
      have hbeta : (fun k => w k * gens k (t ⟨l, hl⟩)) n
          = w n * gens n (t ⟨l, hl⟩) := rfl
      rw [hbeta, hwS n hn, hgens, mul_inv_cancel_left]
  obtain ⟨g, w, hgmem, hw, hwS⟩ := main m le_rfl
  refine ⟨g, hgmem, ?_⟩
  -- the word displaces the basepoint to within `D + 1/4` of `σ` along the fiber
  have hwsmul := tendsto_smul_of_tendsto hw UpperHalfPlane.I
  have hfreq : ∃ᶠ n in Filter.atTop, w n • UpperHalfPlane.I ∈
      Metric.closedBall σ (D + 1) := by
    rw [Filter.frequently_atTop]
    intro a
    obtain ⟨n, hnS, han⟩ := hSinf.exists_gt a
    refine ⟨n, han.le, ?_⟩
    rw [Metric.mem_closedBall, dist_comm]
    have h1 := hbdist n m
    have h2 : ((m : ℕ) : ℝ) / (m : ℝ) = 1 := div_self hm0.ne'
    rw [h2, Path.extend_one] at h1
    rw [hwS n hnS]
    linarith
  have hmem2 := Metric.isClosed_closedBall.mem_of_frequently_of_tendsto hfreq hwsmul
  rw [Metric.mem_closedBall, dist_comm] at hmem2
  exact hmem2

/-- Cocompactness from orbit density: the quotient is the continuous image of a closed
ball. -/
theorem cocompact_of_orbit_dense {Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ)} {D : ℝ}
    (hdense : ∀ σ : UpperHalfPlane, ∃ g ∈ Γ, dist σ (g • UpperHalfPlane.I) ≤ D) :
    CompactSpace (Quotient (MulAction.orbitRel Γ UpperHalfPlane)) := by
  haveI : ContinuousConstSMul (↥Γ) UpperHalfPlane :=
    ⟨fun c => (isometry_smul UpperHalfPlane
      (c : Matrix.SpecialLinearGroup (Fin 2) ℝ)).continuous⟩
  refine ⟨?_⟩
  have himage : (Set.univ : Set (Quotient (MulAction.orbitRel Γ UpperHalfPlane)))
      = Quotient.mk (MulAction.orbitRel Γ UpperHalfPlane) ''
        Metric.closedBall UpperHalfPlane.I D := by
    refine Set.eq_of_subset_of_subset (fun x _ => ?_) (Set.subset_univ _)
    obtain ⟨σ, rfl⟩ := Quotient.exists_rep x
    obtain ⟨g, hgΓ, hgd⟩ := hdense σ
    refine ⟨g⁻¹ • σ, ?_, ?_⟩
    · rw [Metric.mem_closedBall]
      have h1 : dist (g • g⁻¹ • σ) (g • UpperHalfPlane.I) = dist (g⁻¹ • σ) UpperHalfPlane.I :=
        dist_smul g (g⁻¹ • σ) UpperHalfPlane.I
      rw [smul_inv_smul] at h1
      rw [← h1]
      exact hgd
    · exact Quotient.sound (MulAction.orbitRel_apply.mpr
        (MulAction.mem_orbit_iff.mpr ⟨(⟨g, hgΓ⟩ : ↥Γ)⁻¹, rfl⟩))
  rw [himage]
  exact (isCompact_closedBall UpperHalfPlane.I D).image
    MulAction.isOpenQuotientMap_quotientMk.continuous

/-! ## Limit cocompactness and the limit area bound -/

/-- **Limit cocompactness**: the Mumford limit group of a sequence of trace-gapped groups
with uniformly dense orbits and convergent ball-generator tuples is cocompact. -/
theorem limit_group_cocompact {ι : Type} [Finite ι]
    (Γ : ℕ → Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ))
    {D : ℝ} (hD : 0 ≤ D)
    (hdense : ∀ n σ, Metric.infDist σ (MulAction.orbit (Γ n) UpperHalfPlane.I) ≤ D)
    (gens : ℕ → ι → Matrix.SpecialLinearGroup (Fin 2) ℝ)
    (hmem : ∀ n i, gens n i ∈ Γ n)
    (hball : ∀ n, ∀ γ ∈ Γ n, dist UpperHalfPlane.I (γ • UpperHalfPlane.I) ≤ 2 * D + 1 →
      ∃ i, gens n i = γ)
    (ρ : ι → Matrix.SpecialLinearGroup (Fin 2) ℝ)
    (hlim : ∀ i, Filter.Tendsto (fun n => gens n i) Filter.atTop (nhds (ρ i))) :
    CompactSpace (Quotient (MulAction.orbitRel (Subgroup.closure (Set.range ρ))
      UpperHalfPlane)) :=
  cocompact_of_orbit_dense (limit_orbit_dense Γ hD hdense gens hmem hball ρ hlim)

/-- The limit group carries the explicit covering-volume bound of the closed
`(D + 1)`-ball. -/
theorem hasAreaBound_limit_group {ι : Type} [Finite ι]
    (Γ : ℕ → Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ))
    {D : ℝ} (hD : 0 ≤ D)
    (hdense : ∀ n σ, Metric.infDist σ (MulAction.orbit (Γ n) UpperHalfPlane.I) ≤ D)
    (gens : ℕ → ι → Matrix.SpecialLinearGroup (Fin 2) ℝ)
    (hmem : ∀ n i, gens n i ∈ Γ n)
    (hball : ∀ n, ∀ γ ∈ Γ n, dist UpperHalfPlane.I (γ • UpperHalfPlane.I) ≤ 2 * D + 1 →
      ∃ i, gens n i = γ)
    (ρ : ι → Matrix.SpecialLinearGroup (Fin 2) ℝ)
    (hlim : ∀ i, Filter.Tendsto (fun n => gens n i) Filter.atTop (nhds (ρ i))) :
    HasAreaBound (Subgroup.closure (Set.range ρ))
      (volume (Metric.closedBall UpperHalfPlane.I (D + 1))) := by
  have hdense' := limit_orbit_dense Γ hD hdense gens hmem hball ρ hlim
  refine ⟨Metric.closedBall UpperHalfPlane.I (D + 1), measurableSet_closedBall,
    Filter.Eventually.of_forall fun τ => ?_, le_rfl⟩
  obtain ⟨g, hg, hgd⟩ := hdense' τ
  refine ⟨⟨g⁻¹, inv_mem hg⟩, ?_⟩
  rw [Metric.mem_closedBall, Subgroup.smul_def]
  have h1 : dist (g • g⁻¹ • τ) (g • UpperHalfPlane.I) = dist (g⁻¹ • τ) UpperHalfPlane.I :=
    dist_smul g (g⁻¹ • τ) UpperHalfPlane.I
  rw [smul_inv_smul] at h1
  rw [← h1]
  exact hgd

/-! ## Thick Mumford subconvergence -/

/-- **Thick Mumford subconvergence, self-contained form.** A sequence of representatives
with systole at least `ε > 0` and covering-volume bound `A < ∞` carries ball-generator
tuples of the uniform size `ballGensCard ε (2 D + 1)`, `D = mumfordDensityBound A ε`, which
generate the groups, satisfy the displacement bound automatically, and subconverge to a
tuple generating a trace-gapped, free, Fuchsian, cocompact limit group carrying the explicit
covering-volume bound of the closed `(D + 1)`-ball. -/
theorem mumford_subconvergence_thick {Γ₀ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℝ)}
    (hΓ₀ : IsFuchsianGroup Γ₀)
    (hfree : ∀ γ : Γ₀, (∃ τ : UpperHalfPlane, γ • τ = τ) →
      ∀ τ' : UpperHalfPlane, γ • τ' = τ')
    (hcc : CompactSpace (Quotient (MulAction.orbitRel Γ₀ UpperHalfPlane)))
    {ε : ℝ} (hε : 0 < ε) {A : ℝ≥0∞} (hA : A ≠ ⊤)
    (x : ℕ → TeichRep Γ₀) (hthick : ∀ n, ε ≤ systoleRep (x n))
    (harea : ∀ n, HasAreaBound (x n).group A) :
    ∃ (φ : ℕ → ℕ)
      (gens : ℕ → Fin (ballGensCard ε (2 * mumfordDensityBound A ε + 1)) →
        Matrix.SpecialLinearGroup (Fin 2) ℝ)
      (ρ : Fin (ballGensCard ε (2 * mumfordDensityBound A ε + 1)) →
        Matrix.SpecialLinearGroup (Fin 2) ℝ),
      StrictMono φ ∧
      (∀ k i, gens k i ∈ (x (φ k)).group) ∧
      (∀ k, Subgroup.closure (Set.range (gens k)) = (x (φ k)).group) ∧
      (∀ i, Filter.Tendsto (fun k => gens k i) Filter.atTop (nhds (ρ i))) ∧
      (∀ h ∈ Subgroup.closure (Set.range ρ), actsNontrivially h →
        2 * Real.cosh (ε / 2) ≤ |Matrix.trace (h : Matrix (Fin 2) (Fin 2) ℝ)|) ∧
      IsFuchsianGroup (Subgroup.closure (Set.range ρ)) ∧
      (∀ h : Subgroup.closure (Set.range ρ), (∃ τ : UpperHalfPlane, h • τ = τ) →
        ∀ τ' : UpperHalfPlane, h • τ' = τ') ∧
      CompactSpace (Quotient (MulAction.orbitRel (Subgroup.closure (Set.range ρ))
        UpperHalfPlane)) ∧
      HasAreaBound (Subgroup.closure (Set.range ρ))
        (volume (Metric.closedBall UpperHalfPlane.I (mumfordDensityBound A ε + 1))) := by
  classical
  -- the cocompactness of the base is carried by the area hypothesis
  have _ := hcc
  -- nonnegativity of the density and displacement bounds
  have hD0 : 0 ≤ mumfordDensityBound A ε := by
    unfold mumfordDensityBound
    have h1 : (0 : ℝ) ≤ (2 * A / upperBallVolume (ε / 8)).toReal := ENNReal.toReal_nonneg
    nlinarith [mul_nonneg h1 (by linarith : (0 : ℝ) ≤ ε / 4)]
  have hR0 : 0 ≤ 2 * mumfordDensityBound A ε + 1 := by linarith
  -- each group is Fuchsian with translation-length gap `ε`
  have hfuch : ∀ n, IsFuchsianGroup (x n).group := fun n =>
    TeichRep.isFuchsian_group hΓ₀ hfree (x n)
  have hgap : ∀ n, ∀ γ ∈ (x n).group, actsNontrivially γ → ε ≤ translationLength γ :=
    fun n γ hγ hnt => (hthick n).trans (systoleRep_le (x n) hγ hnt)
  -- the packing bound makes every orbit `D`-dense
  have hdense : ∀ n σ, Metric.infDist σ (MulAction.orbit (x n).group UpperHalfPlane.I)
      ≤ mumfordDensityBound A ε := fun n σ =>
    orbit_infDist_le_of_hasAreaBound (hfuch n) hε (hgap n) hA (harea n) σ UpperHalfPlane.I
  -- ball-generator tuples of the pinned uniform size
  have hex : ∀ n, ∃ g : Fin (ballGensCard ε (2 * mumfordDensityBound A ε + 1)) →
      Matrix.SpecialLinearGroup (Fin 2) ℝ,
      (∀ i, g i ∈ (x n).group) ∧
      (∀ i, dist UpperHalfPlane.I (g i • UpperHalfPlane.I)
        ≤ 2 * mumfordDensityBound A ε + 1) ∧
      (∀ γ ∈ (x n).group, dist UpperHalfPlane.I (γ • UpperHalfPlane.I)
        ≤ 2 * mumfordDensityBound A ε + 1 → ∃ i, g i = γ) := by
    intro n
    obtain ⟨m, g, hm, h1, h2, h3⟩ := exists_ball_gens_tuple (hfuch n) hε hR0 (hgap n)
    subst hm
    exact ⟨g, h1, h2, h3⟩
  choose gens0 hmem0 hdisp0 hball0 using hex
  -- the tuple ranges are the displacement balls, so their closures recover the groups
  have hclosure : ∀ n, Subgroup.closure (Set.range (gens0 n)) = (x n).group := by
    intro n
    have hset : Set.range (gens0 n) = {γ : Matrix.SpecialLinearGroup (Fin 2) ℝ |
        γ ∈ (x n).group ∧ dist UpperHalfPlane.I (γ • UpperHalfPlane.I)
          ≤ 2 * mumfordDensityBound A ε + 1} := by
      apply Set.eq_of_subset_of_subset
      · rintro γ ⟨i, rfl⟩
        exact ⟨hmem0 n i, hdisp0 n i⟩
      · rintro γ ⟨hγ, hd⟩
        exact hball0 n γ hγ hd
    rw [hset]
    exact closure_ball_generators_eq hD0 (hdense n)
  -- Bolzano–Weierstrass subconvergence of the tuples
  obtain ⟨φ, ρ, hφ, hconv⟩ := exists_subseq_tendsto_sl2_of_bounded gens0 hdisp0
  -- the trace gap passes to the limit group
  have hgapn : ∀ k, ∀ γ ∈ (x (φ k)).group, actsNontrivially γ →
      2 * Real.cosh (ε / 2) ≤ |Matrix.trace (γ : Matrix (Fin 2) (Fin 2) ℝ)| :=
    fun k γ hγ hnt => (trace_gap_of_systole hε (hthick (φ k)) hγ hnt).1
  have hgapρ := limit_trace_gap hε (fun k => (x (φ k)).group)
    (fun k i => gens0 (φ k) i) (fun k i => hmem0 (φ k) i) hgapn ρ hconv
  -- density transports along the subsequence, so the limit group is cocompact
  have hcc' := limit_group_cocompact (fun k => (x (φ k)).group) hD0
    (fun k σ => hdense (φ k) σ) (fun k i => gens0 (φ k) i) (fun k i => hmem0 (φ k) i)
    (fun k γ hγ hd => hball0 (φ k) γ hγ hd) ρ hconv
  -- the explicit covering-volume bound of the limit group
  have harea' := hasAreaBound_limit_group (fun k => (x (φ k)).group) hD0
    (fun k σ => hdense (φ k) σ) (fun k i => gens0 (φ k) i) (fun k i => hmem0 (φ k) i)
    (fun k γ hγ hd => hball0 (φ k) γ hγ hd) ρ hconv
  exact ⟨φ, fun k => gens0 (φ k), ρ, hφ, fun k i => hmem0 (φ k) i,
    fun k => hclosure (φ k), hconv, hgapρ, isFuchsianGroup_of_trace_gap hε hgapρ,
    free_of_trace_gap hε hgapρ, hcc', harea'⟩

end RiemannDynamics
