import RiemannDynamics.Uniformization.Perron.SurfaceHarmonic
import Mathlib.Topology.Homotopy.Path
import Mathlib.Topology.Covering.Basic
import Mathlib.Topology.Homotopy.Lifting
import Mathlib.AlgebraicTopology.FundamentalGroupoid.SimplyConnected

/-!
# The universal path cover of a surface

The universal cover of a connected charted `ℂ`-surface, realized concretely as
the space of homotopy classes of paths from a fixed basepoint. A point of the
cover is an endpoint together with a homotopy class of paths from the
basepoint to it; the topology is generated by the sheets: continuations of a
fixed class by paths running inside a fixed open set. Chart balls are simply
connected, so the projection to the endpoint is a covering map, and the total
space is simply connected.

The cover carries the charted-space and analytic-manifold structures pulled
back through the local homeomorphisms, the projection reads as the identity
in suitable charts upstairs and downstairs, and the homotopy classes of loops
at the basepoint act by deck transformations, transitively on each fiber.

Main declarations:
* `PathCover`, `pathCoverProj`, `pathCoverSheet`, `pathCoverBase`,
  `pathCoverDeck`;
* `pathCoverProj_isCoveringMap` — the projection is a covering map;
* `pathConnectedSpace_pathCover`, `simplyConnectedSpace_pathCover`,
  `t2space_pathCover`, `noncompactSpace_pathCover` — topology of the total
  space;
* the `ChartedSpace ℂ` instance and `isManifold_pathCover`;
* `exists_charts_pathCoverProj_comm` — charts in the maximal atlases reading
  the projection as the identity;
* `exists_pathCoverDeck_diffeomorph`, `pathCoverDeck_transitive` — the deck
  action;
* `finite_fiber_inter_compact` — fibers meet compact sets in finite sets.
-/

open Metric Topology Filter TopologicalSpace
open scoped Manifold ContDiff unitInterval

namespace RiemannDynamics

variable {M : Type*} [TopologicalSpace M]

/-- A point of the universal path cover: an endpoint together with a homotopy
class of paths from the basepoint to it. -/
structure PathCover (x₀ : M) where
  /-- The endpoint on the base surface. -/
  pt : M
  /-- The homotopy class of paths from the basepoint to the endpoint. -/
  cls : Path.Homotopic.Quotient x₀ pt

variable (x₀ : M)

/-- The covering projection: a path class is sent to its endpoint. -/
def pathCoverProj (pc : PathCover x₀) : M := pc.pt

/-- The sheet of the path cover through `pc` over a set `U`: continuations of
the class of `pc` by paths running inside `U`. -/
def pathCoverSheet (pc : PathCover x₀) (U : Set M) : Set (PathCover x₀) :=
  {qc | ∃ η : Path pc.pt qc.pt, (∀ t, η t ∈ U) ∧ qc.cls = pc.cls.trans ⟦η⟧}

/-- The topology of the path cover, generated by the sheets over open sets
containing the endpoint. -/
instance : TopologicalSpace (PathCover x₀) :=
  TopologicalSpace.generateFrom
    {s | ∃ (pc : PathCover x₀) (U : Set M), IsOpen U ∧ pc.pt ∈ U ∧
      s = pathCoverSheet x₀ pc U}

/-- The canonical basepoint of the path cover: the class of the constant
path. -/
def pathCoverBase : PathCover x₀ := ⟨x₀, ⟦Path.refl x₀⟧⟩

/-- The deck transformation associated with a homotopy class of loops at the
basepoint: precomposition of path classes. -/
noncomputable def pathCoverDeck (γ : Path.Homotopic.Quotient x₀ x₀) (pc : PathCover x₀) :
    PathCover x₀ :=
  ⟨pc.pt, γ.trans pc.cls⟩

theorem pathCoverProj_deck (γ : Path.Homotopic.Quotient x₀ x₀)
    (pc : PathCover x₀) :
    pathCoverProj x₀ (pathCoverDeck x₀ γ pc) = pathCoverProj x₀ pc := rfl

variable [ChartedSpace ℂ M]

/-- **The projection of the path cover is a covering map**: chart balls are
evenly covered by their sheets. -/
theorem pathCoverProj_isCoveringMap : IsCoveringMap (pathCoverProj x₀) := by
  classical
  -- Chart-ball disc neighborhoods: inside any open set around a point there is an open
  -- neighborhood which is chart-linearly path connected and homotopy-simply connected.
  have hdisc : ∀ (y : M) (W : Set M), IsOpen W → y ∈ W →
      ∃ V : Set M, V ⊆ W ∧ IsOpen V ∧ y ∈ V ∧
        (∀ z, z ∈ V → ∀ w, w ∈ V → ∃ η : Path z w, ∀ t, η t ∈ V) ∧
        (∀ (a b : M) (η₁ η₂ : Path a b), (∀ t, η₁ t ∈ V) → (∀ t, η₂ t ∈ V) →
          (⟦η₁⟧ : Path.Homotopic.Quotient a b) = ⟦η₂⟧) := by
    intro y W hW hyW
    set φ := chartAt ℂ y
    have hy : y ∈ φ.source := mem_chart_source ℂ y
    have hOopen : IsOpen (φ.target ∩ φ.symm ⁻¹' (W ∩ φ.source)) :=
      φ.continuousOn_symm.isOpen_inter_preimage φ.open_target (hW.inter φ.open_source)
    have hyO : φ y ∈ φ.target ∩ φ.symm ⁻¹' (W ∩ φ.source) := by
      refine ⟨φ.map_source hy, ?_⟩
      rw [Set.mem_preimage, φ.left_inv hy]
      exact ⟨hyW, hy⟩
    obtain ⟨r, hr0, hball⟩ := Metric.isOpen_iff.mp hOopen (φ y) hyO
    have hmemV : ∀ c ∈ Metric.ball (φ y) r,
        φ.symm c ∈ φ.source ∩ φ ⁻¹' Metric.ball (φ y) r := by
      intro c hc
      refine ⟨φ.map_target (hball hc).1, ?_⟩
      rw [Set.mem_preimage, φ.right_inv (hball hc).1]
      exact hc
    refine ⟨φ.source ∩ φ ⁻¹' Metric.ball (φ y) r, ?_, ?_, ⟨hy, ?_⟩, ?_, ?_⟩
    · intro z hz
      have h3 : φ.symm (φ z) ∈ W ∩ φ.source := (hball hz.2).2
      rw [φ.left_inv hz.1] at h3
      exact h3.1
    · exact φ.continuousOn.isOpen_inter_preimage φ.open_source Metric.isOpen_ball
    · exact Metric.mem_ball_self hr0
    · intro z hz w hw
      have hcm : ∀ t : I, (1 - (t : ℝ)) • φ z + (t : ℝ) • φ w ∈ Metric.ball (φ y) r := by
        intro t
        have h1 : (0 : ℝ) ≤ 1 - (t : ℝ) := by
          have := t.2.2
          linarith
        exact (convex_ball (φ y) r) hz.2 hw.2 h1 t.2.1 (by ring)
      have hcombo : Continuous fun t : I => (1 - (t : ℝ)) • φ z + (t : ℝ) • φ w := by
        have hcoe : Continuous fun t : I => (t : ℝ) := continuous_subtype_val
        have h2 : Continuous fun t : I =>
            ((1 - (t : ℝ) : ℝ) : ℂ) * φ z + ((t : ℝ) : ℂ) * φ w :=
          ((Complex.continuous_ofReal.comp (continuous_const.sub hcoe)).mul
            continuous_const).add ((Complex.continuous_ofReal.comp hcoe).mul continuous_const)
        refine h2.congr fun t => ?_
        rw [Complex.real_smul, Complex.real_smul]
      refine ⟨⟨⟨fun t => φ.symm ((1 - (t : ℝ)) • φ z + (t : ℝ) • φ w), ?_⟩, ?_, ?_⟩, ?_⟩
      · exact φ.continuousOn_symm.comp_continuous hcombo fun t => (hball (hcm t)).1
      · change φ.symm ((1 - ((0 : I) : ℝ)) • φ z + ((0 : I) : ℝ) • φ w) = z
        norm_num
        exact φ.left_inv hz.1
      · change φ.symm ((1 - ((1 : I) : ℝ)) • φ z + ((1 : I) : ℝ) • φ w) = w
        norm_num
        exact φ.left_inv hw.1
      · intro t
        exact hmemV _ (hcm t)
    · intro a b η₁ η₂ hη₁ hη₂
      have hcm : ∀ st : I × I,
          (1 - (st.1 : ℝ)) • φ (η₁ st.2) + (st.1 : ℝ) • φ (η₂ st.2) ∈
            Metric.ball (φ y) r := by
        intro st
        have h1 : (0 : ℝ) ≤ 1 - (st.1 : ℝ) := by
          have := st.1.2.2
          linarith
        exact (convex_ball (φ y) r) (hη₁ st.2).2 (hη₂ st.2).2 h1 st.1.2.1 (by ring)
      have hc1 : Continuous fun st : I × I => φ (η₁ st.2) :=
        φ.continuousOn.comp_continuous (η₁.continuous.comp continuous_snd)
          fun st => (hη₁ st.2).1
      have hc2 : Continuous fun st : I × I => φ (η₂ st.2) :=
        φ.continuousOn.comp_continuous (η₂.continuous.comp continuous_snd)
          fun st => (hη₂ st.2).1
      have hcombo : Continuous fun st : I × I =>
          (1 - (st.1 : ℝ)) • φ (η₁ st.2) + (st.1 : ℝ) • φ (η₂ st.2) := by
        have hcoe : Continuous fun st : I × I => (st.1 : ℝ) :=
          continuous_subtype_val.comp continuous_fst
        have h2 : Continuous fun st : I × I =>
            ((1 - (st.1 : ℝ) : ℝ) : ℂ) * φ (η₁ st.2) + ((st.1 : ℝ) : ℂ) * φ (η₂ st.2) :=
          ((Complex.continuous_ofReal.comp (continuous_const.sub hcoe)).mul hc1).add
            ((Complex.continuous_ofReal.comp hcoe).mul hc2)
        refine h2.congr fun st => ?_
        rw [Complex.real_smul, Complex.real_smul]
      refine Quotient.sound ⟨⟨⟨⟨fun st =>
        φ.symm ((1 - (st.1 : ℝ)) • φ (η₁ st.2) + (st.1 : ℝ) • φ (η₂ st.2)), ?_⟩, ?_, ?_⟩, ?_⟩⟩
      · exact φ.continuousOn_symm.comp_continuous hcombo fun st => (hball (hcm st)).1
      · intro t
        change φ.symm ((1 - ((0 : I) : ℝ)) • φ (η₁ t) + ((0 : I) : ℝ) • φ (η₂ t)) = η₁ t
        norm_num
        exact φ.left_inv (hη₁ t).1
      · intro t
        change φ.symm ((1 - ((1 : I) : ℝ)) • φ (η₁ t) + ((1 : I) : ℝ) • φ (η₂ t)) = η₂ t
        norm_num
        exact φ.left_inv (hη₂ t).1
      · intro s t ht
        have hcoinc : η₁ t = η₂ t := by
          rcases ht with h0 | h1
          · rw [h0, η₁.source, η₂.source]
          · rw [Set.mem_singleton_iff] at h1
            rw [h1, η₁.target, η₂.target]
        have hmemsrc : η₁ t ∈ φ.source := (hη₁ t).1
        change φ.symm ((1 - (s : ℝ)) • φ (η₁ t) + (s : ℝ) • φ (η₂ t)) = η₁ t
        rw [← hcoinc]
        have hone : (1 - (s : ℝ)) • φ (η₁ t) + (s : ℝ) • φ (η₁ t) = φ (η₁ t) := by
          module
        rw [hone]
        exact φ.left_inv hmemsrc
  -- Concatenations of paths inside a set stay inside the set.
  have htmem : ∀ (S : Set M) {a b c : M} (p : Path a b) (q : Path b c),
      (∀ t, p t ∈ S) → (∀ t, q t ∈ S) → ∀ t, (p.trans q) t ∈ S := by
    intro S a b c p q hp hq t
    have h := Set.mem_range_self (f := ⇑(p.trans q)) t
    rw [Path.trans_range] at h
    rcases h with ⟨s, hs⟩ | ⟨s, hs⟩
    · exact hs ▸ hp s
    · exact hs ▸ hq s
  -- Concatenation of homotopy classes of paths.
  have hq1 : ∀ {a b c : M} (p : Path a b) (q : Path b c),
      Path.Homotopic.Quotient.trans ⟦p⟧ ⟦q⟧ = (⟦p.trans q⟧ : Path.Homotopic.Quotient a c) := by
    intros
    rfl
  -- Sheets over opens around the endpoint are basic opens.
  have hsheet_open : ∀ (qc : PathCover x₀) (U : Set M), IsOpen U → qc.pt ∈ U →
      IsOpen (pathCoverSheet x₀ qc U) := fun qc U hU hqU =>
    isOpen_generateFrom_of_mem ⟨qc, U, hU, hqU, rfl⟩
  -- Every point lies on its own sheet.
  have hsheet_self : ∀ (qc : PathCover x₀) (U : Set M), qc.pt ∈ U →
      qc ∈ pathCoverSheet x₀ qc U := fun qc U hqU =>
    ⟨Path.refl qc.pt, fun _ => hqU, (Path.Homotopic.Quotient.trans_refl qc.cls).symm⟩
  -- Members of a sheet have endpoint inside the base open.
  have hsheet_pt : ∀ (qc rc : PathCover x₀) (U : Set M), rc ∈ pathCoverSheet x₀ qc U →
      rc.pt ∈ U := by
    intro qc rc U h
    obtain ⟨η, hη, -⟩ := h
    exact η.target ▸ hη 1
  -- The projection is continuous.
  have hproj_cont : Continuous (pathCoverProj x₀) := by
    rw [continuous_def]
    intro W hW
    rw [isOpen_iff_forall_mem_open]
    intro qc hqc
    obtain ⟨V, hVsub, hVopen, hqV, -, -⟩ := hdisc qc.pt W hW hqc
    exact ⟨pathCoverSheet x₀ qc V, fun rc hrc => hVsub (hsheet_pt qc rc V hrc),
      hsheet_open qc V hVopen hqV, hsheet_self qc V hqV⟩
  -- Continuation along chart-linear paths is continuous into the cover.
  have hslice : ∀ (rc : PathCover x₀) (V : Set M), IsOpen V → ∀ hrcV : rc.pt ∈ V,
      ∀ lin : ∀ z, z ∈ V → ∀ w, w ∈ V → Path z w,
      (∀ z hz w hw t, lin z hz w hw t ∈ V) →
      (∀ (a b : M) (η₁ η₂ : Path a b), (∀ t, η₁ t ∈ V) → (∀ t, η₂ t ∈ V) →
        (⟦η₁⟧ : Path.Homotopic.Quotient a b) = ⟦η₂⟧) →
      Continuous fun y : ↥V =>
        (⟨y.val, rc.cls.trans ⟦lin rc.pt hrcV y.val y.2⟧⟩ : PathCover x₀) := by
    intro rc V hVopen hrcV lin hlin hhomo
    refine continuous_generateFrom_iff.mpr ?_
    rintro s ⟨pc, U, hUopen, -, rfl⟩
    rw [isOpen_iff_forall_mem_open]
    intro y hy
    obtain ⟨η₀, hη₀, hcls₀⟩ := hy
    have hcls₀' : rc.cls.trans ⟦lin rc.pt hrcV y.val y.2⟧ = pc.cls.trans ⟦η₀⟧ := hcls₀
    have hyU : (y : M) ∈ U := by
      have h := hη₀ 1
      rw [η₀.target] at h
      exact h
    obtain ⟨V', hV'sub, hV'open, hyV', hlin', hhomo'⟩ :=
      hdisc y.val (U ∩ V) (hUopen.inter hVopen) ⟨hyU, y.2⟩
    choose lin' hlin' using hlin'
    refine ⟨Subtype.val ⁻¹' V', fun w hw => ?_, hV'open.preimage continuous_subtype_val, hyV'⟩
    refine ⟨η₀.trans (lin' y.val hyV' w.val hw),
      htmem U η₀ (lin' y.val hyV' w.val hw) hη₀ (fun t => (hV'sub (hlin' _ _ _ _ t)).1), ?_⟩
    have hstep : (⟦lin rc.pt hrcV w.val w.2⟧ : Path.Homotopic.Quotient rc.pt w.val) =
        ⟦(lin rc.pt hrcV y.val y.2).trans (lin' y.val hyV' w.val hw)⟧ :=
      hhomo _ _ _ _ (fun t => hlin _ _ _ _ t)
        (htmem V _ _ (fun t => hlin _ _ _ _ t) fun t => (hV'sub (hlin' _ _ _ _ t)).2)
    have hfin : rc.cls.trans ⟦lin rc.pt hrcV w.val w.2⟧ =
        pc.cls.trans ⟦η₀.trans (lin' y.val hyV' w.val hw)⟧ := by
      rw [hstep, ← hq1 (lin rc.pt hrcV y.val y.2) (lin' y.val hyV' w.val hw),
        ← Path.Homotopic.Quotient.trans_assoc, hcls₀', Path.Homotopic.Quotient.trans_assoc,
        hq1]
    exact hfin
  -- The evenly covered neighborhood at a point.
  intro x
  obtain ⟨V, -, hVopen, hxV, hlinE, hhomo⟩ := hdisc x Set.univ isOpen_univ (Set.mem_univ x)
  choose lin hlin using hlinE
  letI : TopologicalSpace (Path.Homotopic.Quotient x₀ x) := ⊥
  haveI : DiscreteTopology (Path.Homotopic.Quotient x₀ x) := ⟨rfl⟩
  -- Retraction to the fiber is constant along sheets over V.
  have hret : ∀ (qc : PathCover x₀) (hq : qc.pt ∈ V) (rc : PathCover x₀),
      rc ∈ pathCoverSheet x₀ qc V → ∀ hr : rc.pt ∈ V,
      rc.cls.trans ⟦lin rc.pt hr x hxV⟧ = qc.cls.trans ⟦lin qc.pt hq x hxV⟧ := by
    intro qc hq rc hrc hr
    obtain ⟨η, hη, hcls⟩ := hrc
    have hcls' : rc.cls = qc.cls.trans ⟦η⟧ := hcls
    rw [hcls', Path.Homotopic.Quotient.trans_assoc, hq1 η (lin rc.pt hr x hxV),
      hhomo _ _ (η.trans (lin rc.pt hr x hxV)) (lin qc.pt hq x hxV)
        (htmem V η (lin rc.pt hr x hxV) hη fun t => hlin _ _ _ _ t)
        fun t => hlin _ _ _ _ t]
  -- The preimage of V is open: it is a union of sheets.
  have hpreV : IsOpen (pathCoverProj x₀ ⁻¹' V) := by
    rw [isOpen_iff_forall_mem_open]
    intro qc hqc
    exact ⟨pathCoverSheet x₀ qc V, fun rc hrc => hsheet_pt qc rc V hrc,
      hsheet_open qc V hVopen hqc, hsheet_self qc V hqc⟩
  suffices hev : IsEvenlyCovered (pathCoverProj x₀) x (Path.Homotopic.Quotient x₀ x) from
    hev.to_isEvenlyCovered_preimage
  refine ⟨inferInstance, V, hxV, hVopen, hpreV, ?_⟩
  refine ⟨{ toFun := fun qc =>
              (⟨pathCoverProj x₀ qc.val, qc.2⟩, qc.val.cls.trans ⟦lin qc.val.pt qc.2 x hxV⟧)
            invFun := fun p => ⟨⟨p.1.val, p.2.trans ⟦lin x hxV p.1.val p.1.2⟧⟩, p.1.2⟩
            left_inv := ?_
            right_inv := ?_
            continuous_toFun := ?_
            continuous_invFun := ?_ }, fun _ => rfl⟩
  · rintro ⟨⟨pt, cls⟩, hq⟩
    have hloop : Path.Homotopic.Quotient.trans
        (⟦lin pt hq x hxV⟧ : Path.Homotopic.Quotient pt x) ⟦lin x hxV pt hq⟧ =
        Path.Homotopic.Quotient.refl pt := by
      rw [hq1]
      exact hhomo _ _ _ _
        (htmem V (lin pt hq x hxV) (lin x hxV pt hq) (fun t => hlin _ _ _ _ t)
          fun t => hlin _ _ _ _ t)
        fun _ => hq
    have hC : (cls.trans ⟦lin pt hq x hxV⟧).trans ⟦lin x hxV pt hq⟧ = cls := by
      rw [Path.Homotopic.Quotient.trans_assoc, hloop, Path.Homotopic.Quotient.trans_refl]
    exact Subtype.ext (congrArg (PathCover.mk pt) hC)
  · rintro ⟨⟨y, hy⟩, c⟩
    have hloop : Path.Homotopic.Quotient.trans
        (⟦lin x hxV y hy⟧ : Path.Homotopic.Quotient x y) ⟦lin y hy x hxV⟧ =
        Path.Homotopic.Quotient.refl x := by
      rw [hq1]
      exact hhomo _ _ _ _
        (htmem V (lin x hxV y hy) (lin y hy x hxV) (fun t => hlin _ _ _ _ t)
          fun t => hlin _ _ _ _ t)
        fun _ => hxV
    have hC : (c.trans ⟦lin x hxV y hy⟧).trans ⟦lin y hy x hxV⟧ = c := by
      rw [Path.Homotopic.Quotient.trans_assoc, hloop, Path.Homotopic.Quotient.trans_refl]
    exact Prod.ext (Subtype.ext rfl) hC
  · refine Continuous.prodMk
      ((hproj_cont.comp continuous_subtype_val).subtype_mk fun qc => qc.2) ?_
    rw [continuous_discrete_rng]
    intro b
    rw [isOpen_iff_forall_mem_open]
    intro qc hqc
    refine ⟨Subtype.val ⁻¹' pathCoverSheet x₀ qc.val V, fun rc hrc => ?_,
      (hsheet_open qc.val V hVopen qc.2).preimage continuous_subtype_val,
      hsheet_self qc.val V qc.2⟩
    have h1 : rc.val.cls.trans ⟦lin rc.val.pt rc.2 x hxV⟧ =
        qc.val.cls.trans ⟦lin qc.val.pt qc.2 x hxV⟧ := hret qc.val qc.2 rc.val hrc rc.2
    have h2 : qc.val.cls.trans ⟦lin qc.val.pt qc.2 x hxV⟧ = b := hqc
    exact h1.trans h2
  · rw [continuous_prod_of_discrete_right]
    intro c
    exact (hslice ⟨x, c⟩ V hVopen hxV lin hlin hhomo).subtype_mk fun y => y.2

/-- **The local trivialization at a point of the cover**: an open partial
homeomorphism restricting the projection, with target inside the chart source
of the endpoint. -/
theorem exists_pathCover_openPartialHomeomorph (pc : PathCover x₀) :
    ∃ e : OpenPartialHomeomorph (PathCover x₀) M, pc ∈ e.source ∧
      (∀ qc ∈ e.source, e qc = pathCoverProj x₀ qc) ∧
      e.target ⊆ (chartAt ℂ (pathCoverProj x₀ pc)).source := by
  classical
  -- Chart-ball disc neighborhoods: inside any open set around a point there is an open
  -- neighborhood which is chart-linearly path connected and homotopy-simply connected.
  have hdisc : ∀ (y : M) (W : Set M), IsOpen W → y ∈ W →
      ∃ V : Set M, V ⊆ W ∧ IsOpen V ∧ y ∈ V ∧
        (∀ z, z ∈ V → ∀ w, w ∈ V → ∃ η : Path z w, ∀ t, η t ∈ V) ∧
        (∀ (a b : M) (η₁ η₂ : Path a b), (∀ t, η₁ t ∈ V) → (∀ t, η₂ t ∈ V) →
          (⟦η₁⟧ : Path.Homotopic.Quotient a b) = ⟦η₂⟧) := by
    intro y W hW hyW
    set φ := chartAt ℂ y
    have hy : y ∈ φ.source := mem_chart_source ℂ y
    have hOopen : IsOpen (φ.target ∩ φ.symm ⁻¹' (W ∩ φ.source)) :=
      φ.continuousOn_symm.isOpen_inter_preimage φ.open_target (hW.inter φ.open_source)
    have hyO : φ y ∈ φ.target ∩ φ.symm ⁻¹' (W ∩ φ.source) := by
      refine ⟨φ.map_source hy, ?_⟩
      rw [Set.mem_preimage, φ.left_inv hy]
      exact ⟨hyW, hy⟩
    obtain ⟨r, hr0, hball⟩ := Metric.isOpen_iff.mp hOopen (φ y) hyO
    have hmemV : ∀ c ∈ Metric.ball (φ y) r,
        φ.symm c ∈ φ.source ∩ φ ⁻¹' Metric.ball (φ y) r := by
      intro c hc
      refine ⟨φ.map_target (hball hc).1, ?_⟩
      rw [Set.mem_preimage, φ.right_inv (hball hc).1]
      exact hc
    refine ⟨φ.source ∩ φ ⁻¹' Metric.ball (φ y) r, ?_, ?_, ⟨hy, ?_⟩, ?_, ?_⟩
    · intro z hz
      have h3 : φ.symm (φ z) ∈ W ∩ φ.source := (hball hz.2).2
      rw [φ.left_inv hz.1] at h3
      exact h3.1
    · exact φ.continuousOn.isOpen_inter_preimage φ.open_source Metric.isOpen_ball
    · exact Metric.mem_ball_self hr0
    · intro z hz w hw
      have hcm : ∀ t : I, (1 - (t : ℝ)) • φ z + (t : ℝ) • φ w ∈ Metric.ball (φ y) r := by
        intro t
        have h1 : (0 : ℝ) ≤ 1 - (t : ℝ) := by
          have := t.2.2
          linarith
        exact (convex_ball (φ y) r) hz.2 hw.2 h1 t.2.1 (by ring)
      have hcombo : Continuous fun t : I => (1 - (t : ℝ)) • φ z + (t : ℝ) • φ w := by
        have hcoe : Continuous fun t : I => (t : ℝ) := continuous_subtype_val
        have h2 : Continuous fun t : I =>
            ((1 - (t : ℝ) : ℝ) : ℂ) * φ z + ((t : ℝ) : ℂ) * φ w :=
          ((Complex.continuous_ofReal.comp (continuous_const.sub hcoe)).mul
            continuous_const).add ((Complex.continuous_ofReal.comp hcoe).mul continuous_const)
        refine h2.congr fun t => ?_
        rw [Complex.real_smul, Complex.real_smul]
      refine ⟨⟨⟨fun t => φ.symm ((1 - (t : ℝ)) • φ z + (t : ℝ) • φ w), ?_⟩, ?_, ?_⟩, ?_⟩
      · exact φ.continuousOn_symm.comp_continuous hcombo fun t => (hball (hcm t)).1
      · change φ.symm ((1 - ((0 : I) : ℝ)) • φ z + ((0 : I) : ℝ) • φ w) = z
        norm_num
        exact φ.left_inv hz.1
      · change φ.symm ((1 - ((1 : I) : ℝ)) • φ z + ((1 : I) : ℝ) • φ w) = w
        norm_num
        exact φ.left_inv hw.1
      · intro t
        exact hmemV _ (hcm t)
    · intro a b η₁ η₂ hη₁ hη₂
      have hcm : ∀ st : I × I,
          (1 - (st.1 : ℝ)) • φ (η₁ st.2) + (st.1 : ℝ) • φ (η₂ st.2) ∈
            Metric.ball (φ y) r := by
        intro st
        have h1 : (0 : ℝ) ≤ 1 - (st.1 : ℝ) := by
          have := st.1.2.2
          linarith
        exact (convex_ball (φ y) r) (hη₁ st.2).2 (hη₂ st.2).2 h1 st.1.2.1 (by ring)
      have hc1 : Continuous fun st : I × I => φ (η₁ st.2) :=
        φ.continuousOn.comp_continuous (η₁.continuous.comp continuous_snd)
          fun st => (hη₁ st.2).1
      have hc2 : Continuous fun st : I × I => φ (η₂ st.2) :=
        φ.continuousOn.comp_continuous (η₂.continuous.comp continuous_snd)
          fun st => (hη₂ st.2).1
      have hcombo : Continuous fun st : I × I =>
          (1 - (st.1 : ℝ)) • φ (η₁ st.2) + (st.1 : ℝ) • φ (η₂ st.2) := by
        have hcoe : Continuous fun st : I × I => (st.1 : ℝ) :=
          continuous_subtype_val.comp continuous_fst
        have h2 : Continuous fun st : I × I =>
            ((1 - (st.1 : ℝ) : ℝ) : ℂ) * φ (η₁ st.2) + ((st.1 : ℝ) : ℂ) * φ (η₂ st.2) :=
          ((Complex.continuous_ofReal.comp (continuous_const.sub hcoe)).mul hc1).add
            ((Complex.continuous_ofReal.comp hcoe).mul hc2)
        refine h2.congr fun st => ?_
        rw [Complex.real_smul, Complex.real_smul]
      refine Quotient.sound ⟨⟨⟨⟨fun st =>
        φ.symm ((1 - (st.1 : ℝ)) • φ (η₁ st.2) + (st.1 : ℝ) • φ (η₂ st.2)), ?_⟩, ?_, ?_⟩, ?_⟩⟩
      · exact φ.continuousOn_symm.comp_continuous hcombo fun st => (hball (hcm st)).1
      · intro t
        change φ.symm ((1 - ((0 : I) : ℝ)) • φ (η₁ t) + ((0 : I) : ℝ) • φ (η₂ t)) = η₁ t
        norm_num
        exact φ.left_inv (hη₁ t).1
      · intro t
        change φ.symm ((1 - ((1 : I) : ℝ)) • φ (η₁ t) + ((1 : I) : ℝ) • φ (η₂ t)) = η₂ t
        norm_num
        exact φ.left_inv (hη₂ t).1
      · intro s t ht
        have hcoinc : η₁ t = η₂ t := by
          rcases ht with h0 | h1
          · rw [h0, η₁.source, η₂.source]
          · rw [Set.mem_singleton_iff] at h1
            rw [h1, η₁.target, η₂.target]
        have hmemsrc : η₁ t ∈ φ.source := (hη₁ t).1
        change φ.symm ((1 - (s : ℝ)) • φ (η₁ t) + (s : ℝ) • φ (η₂ t)) = η₁ t
        rw [← hcoinc]
        have hone : (1 - (s : ℝ)) • φ (η₁ t) + (s : ℝ) • φ (η₁ t) = φ (η₁ t) := by
          module
        rw [hone]
        exact φ.left_inv hmemsrc
  -- Concatenations of paths inside a set stay inside the set.
  have htmem : ∀ (S : Set M) {a b c : M} (p : Path a b) (q : Path b c),
      (∀ t, p t ∈ S) → (∀ t, q t ∈ S) → ∀ t, (p.trans q) t ∈ S := by
    intro S a b c p q hp hq t
    have h := Set.mem_range_self (f := ⇑(p.trans q)) t
    rw [Path.trans_range] at h
    rcases h with ⟨s, hs⟩ | ⟨s, hs⟩
    · exact hs ▸ hp s
    · exact hs ▸ hq s
  -- Concatenation of homotopy classes of paths.
  have hq1 : ∀ {a b c : M} (p : Path a b) (q : Path b c),
      Path.Homotopic.Quotient.trans ⟦p⟧ ⟦q⟧ = (⟦p.trans q⟧ : Path.Homotopic.Quotient a c) := by
    intros
    rfl
  -- Sheets over opens around the endpoint are basic opens.
  have hsheet_open : ∀ (qc : PathCover x₀) (U : Set M), IsOpen U → qc.pt ∈ U →
      IsOpen (pathCoverSheet x₀ qc U) := fun qc U hU hqU =>
    isOpen_generateFrom_of_mem ⟨qc, U, hU, hqU, rfl⟩
  -- Every point lies on its own sheet.
  have hsheet_self : ∀ (qc : PathCover x₀) (U : Set M), qc.pt ∈ U →
      qc ∈ pathCoverSheet x₀ qc U := fun qc U hqU =>
    ⟨Path.refl qc.pt, fun _ => hqU, (Path.Homotopic.Quotient.trans_refl qc.cls).symm⟩
  -- Members of a sheet have endpoint inside the base open.
  have hsheet_pt : ∀ (qc rc : PathCover x₀) (U : Set M), rc ∈ pathCoverSheet x₀ qc U →
      rc.pt ∈ U := by
    intro qc rc U h
    obtain ⟨η, hη, -⟩ := h
    exact η.target ▸ hη 1
  -- The projection is continuous.
  have hproj_cont : Continuous (pathCoverProj x₀) := by
    rw [continuous_def]
    intro W hW
    rw [isOpen_iff_forall_mem_open]
    intro qc hqc
    obtain ⟨V, hVsub, hVopen, hqV, -, -⟩ := hdisc qc.pt W hW hqc
    exact ⟨pathCoverSheet x₀ qc V, fun rc hrc => hVsub (hsheet_pt qc rc V hrc),
      hsheet_open qc V hVopen hqV, hsheet_self qc V hqV⟩
  -- Continuation along chart-linear paths is continuous into the cover.
  have hslice : ∀ (rc : PathCover x₀) (V : Set M), IsOpen V → ∀ hrcV : rc.pt ∈ V,
      ∀ lin : ∀ z, z ∈ V → ∀ w, w ∈ V → Path z w,
      (∀ z hz w hw t, lin z hz w hw t ∈ V) →
      (∀ (a b : M) (η₁ η₂ : Path a b), (∀ t, η₁ t ∈ V) → (∀ t, η₂ t ∈ V) →
        (⟦η₁⟧ : Path.Homotopic.Quotient a b) = ⟦η₂⟧) →
      Continuous fun y : ↥V =>
        (⟨y.val, rc.cls.trans ⟦lin rc.pt hrcV y.val y.2⟧⟩ : PathCover x₀) := by
    intro rc V hVopen hrcV lin hlin hhomo
    refine continuous_generateFrom_iff.mpr ?_
    rintro s ⟨pc, U, hUopen, -, rfl⟩
    rw [isOpen_iff_forall_mem_open]
    intro y hy
    obtain ⟨η₀, hη₀, hcls₀⟩ := hy
    have hcls₀' : rc.cls.trans ⟦lin rc.pt hrcV y.val y.2⟧ = pc.cls.trans ⟦η₀⟧ := hcls₀
    have hyU : (y : M) ∈ U := by
      have h := hη₀ 1
      rw [η₀.target] at h
      exact h
    obtain ⟨V', hV'sub, hV'open, hyV', hlin', hhomo'⟩ :=
      hdisc y.val (U ∩ V) (hUopen.inter hVopen) ⟨hyU, y.2⟩
    choose lin' hlin' using hlin'
    refine ⟨Subtype.val ⁻¹' V', fun w hw => ?_, hV'open.preimage continuous_subtype_val, hyV'⟩
    refine ⟨η₀.trans (lin' y.val hyV' w.val hw),
      htmem U η₀ (lin' y.val hyV' w.val hw) hη₀ (fun t => (hV'sub (hlin' _ _ _ _ t)).1), ?_⟩
    have hstep : (⟦lin rc.pt hrcV w.val w.2⟧ : Path.Homotopic.Quotient rc.pt w.val) =
        ⟦(lin rc.pt hrcV y.val y.2).trans (lin' y.val hyV' w.val hw)⟧ :=
      hhomo _ _ _ _ (fun t => hlin _ _ _ _ t)
        (htmem V _ _ (fun t => hlin _ _ _ _ t) fun t => (hV'sub (hlin' _ _ _ _ t)).2)
    have hfin : rc.cls.trans ⟦lin rc.pt hrcV w.val w.2⟧ =
        pc.cls.trans ⟦η₀.trans (lin' y.val hyV' w.val hw)⟧ := by
      rw [hstep, ← hq1 (lin rc.pt hrcV y.val y.2) (lin' y.val hyV' w.val hw),
        ← Path.Homotopic.Quotient.trans_assoc, hcls₀', Path.Homotopic.Quotient.trans_assoc,
        hq1]
    exact hfin
  -- Assemble the open partial homeomorphism over a disc neighborhood of the endpoint.
  obtain ⟨V, hVsub, hVopen, hpcV, hlinE, hhomo⟩ :=
    hdisc (pathCoverProj x₀ pc) (chartAt ℂ (pathCoverProj x₀ pc)).source
      (chartAt ℂ (pathCoverProj x₀ pc)).open_source (mem_chart_source ℂ (pathCoverProj x₀ pc))
  choose lin hlin using hlinE
  refine ⟨{ toFun := pathCoverProj x₀
            invFun := fun y =>
              if h : y ∈ V then ⟨y, pc.cls.trans ⟦lin pc.pt hpcV y h⟧⟩ else pc
            source := pathCoverSheet x₀ pc V
            target := V
            map_source' := fun qc hqc => hsheet_pt pc qc V hqc
            map_target' := ?_
            left_inv' := ?_
            right_inv' := ?_
            open_source := hsheet_open pc V hVopen hpcV
            open_target := hVopen
            continuousOn_toFun := hproj_cont.continuousOn
            continuousOn_invFun := ?_ },
        hsheet_self pc V hpcV, fun qc _ => rfl, hVsub⟩
  · intro y hy
    rw [dif_pos hy]
    exact ⟨lin pc.pt hpcV y hy, fun t => hlin _ _ _ _ t, rfl⟩
  · intro qc hqc
    obtain ⟨η, hη, hcls⟩ := hqc
    have hcls' : qc.cls = pc.cls.trans ⟦η⟧ := hcls
    have hq : pathCoverProj x₀ qc ∈ V := by
      have h := hη 1
      rw [η.target] at h
      exact h
    have hfin : pc.cls.trans (⟦lin pc.pt hpcV (pathCoverProj x₀ qc) hq⟧ :
        Path.Homotopic.Quotient pc.pt (pathCoverProj x₀ qc)) = qc.cls := by
      rw [hhomo _ _ (lin pc.pt hpcV (pathCoverProj x₀ qc) hq) η
        (fun t => hlin _ _ _ _ t) hη]
      exact hcls'.symm
    change (if h : pathCoverProj x₀ qc ∈ V then
        (⟨pathCoverProj x₀ qc,
          pc.cls.trans ⟦lin pc.pt hpcV (pathCoverProj x₀ qc) h⟧⟩ : PathCover x₀)
      else pc) = qc
    rw [dif_pos hq]
    exact congrArg (PathCover.mk (pathCoverProj x₀ qc)) hfin
  · intro y hy
    rw [dif_pos hy]
    rfl
  · rw [continuousOn_iff_continuous_restrict]
    refine (hslice pc V hVopen hpcV lin hlin hhomo).congr fun y => ?_
    change (⟨y.val, pc.cls.trans ⟦lin pc.pt hpcV y.val y.2⟧⟩ : PathCover x₀) =
      if h : (y : M) ∈ V then ⟨(y : M), pc.cls.trans ⟦lin pc.pt hpcV (y : M) h⟧⟩ else pc
    rw [dif_pos y.2]

/-- **The path cover is path connected** when the base is connected: the
canonical lift of a representing path joins the basepoint class to any
point. -/
theorem pathConnectedSpace_pathCover [ConnectedSpace M] :
    PathConnectedSpace (PathCover x₀) := by
  sorry

/-- **The path cover is simply connected**: a loop upstairs projects to a
loop whose class fixes the fiber, so it is null homotopic downstairs, and the
homotopy lifts. -/
theorem simplyConnectedSpace_pathCover [ConnectedSpace M] :
    SimplyConnectedSpace (PathCover x₀) := by
  sorry

/-- **The path cover is Hausdorff** over a Hausdorff base: distinct points of
one fiber lie in disjoint sheets, and points of distinct fibers are separated
through the base. -/
theorem t2space_pathCover [T2Space M] : T2Space (PathCover x₀) := by
  sorry

/-- **The path cover of a noncompact connected base is noncompact**: the
projection is a continuous surjection. -/
theorem noncompactSpace_pathCover [ConnectedSpace M] [NoncompactSpace M] :
    NoncompactSpace (PathCover x₀) := by
  sorry

/-- **Fibers meet compact sets in finite sets**: fibers of the covering
projection are closed and discrete over a Hausdorff base. -/
theorem finite_fiber_inter_compact [T2Space M] {K : Set (PathCover x₀)}
    (hK : IsCompact K) (y : M) :
    (pathCoverProj x₀ ⁻¹' {y} ∩ K).Finite := by
  sorry

/-- The charted-space structure of the path cover: the projection restricted
to a sheet, followed by a chart of the base. -/
noncomputable instance : ChartedSpace ℂ (PathCover x₀) where
  atlas := ⋃ pc : PathCover x₀,
    {(Classical.choose (exists_pathCover_openPartialHomeomorph x₀ pc)) ≫ₕ
      chartAt ℂ (pathCoverProj x₀ pc)}
  chartAt pc :=
    (Classical.choose (exists_pathCover_openPartialHomeomorph x₀ pc)) ≫ₕ
      chartAt ℂ (pathCoverProj x₀ pc)
  mem_chart_source pc := by
    obtain ⟨hmem, heq, htgt⟩ :=
      Classical.choose_spec (exists_pathCover_openPartialHomeomorph x₀ pc)
    refine ⟨hmem, Set.mem_preimage.mpr ?_⟩
    rw [OpenPartialHomeomorph.symm_symm, heq pc hmem]
    exact mem_chart_source ℂ (pathCoverProj x₀ pc)
  chart_mem_atlas pc := Set.mem_iUnion.mpr ⟨pc, rfl⟩

variable [IsManifold 𝓘(ℂ) ω M]

/-- **The path cover is an analytic surface**: transition maps factor through
transition maps of the base. -/
theorem isManifold_pathCover : IsManifold 𝓘(ℂ) ω (PathCover x₀) := by
  sorry

instance : IsManifold 𝓘(ℂ) ω (PathCover x₀) := isManifold_pathCover x₀

/-- **The projection reads as the identity in suitable charts**: around any
point of the cover there are charts in the maximal atlases upstairs and
downstairs conjugating the projection to the identity. -/
theorem exists_charts_pathCoverProj_comm (pc : PathCover x₀) :
    ∃ e ∈ IsManifold.maximalAtlas 𝓘(ℂ) ω (PathCover x₀),
      ∃ f ∈ IsManifold.maximalAtlas 𝓘(ℂ) ω M,
        pc ∈ e.source ∧ pathCoverProj x₀ pc ∈ f.source ∧
        (∀ qc ∈ e.source, pathCoverProj x₀ qc ∈ f.source) ∧
        ∀ qc ∈ e.source, f (pathCoverProj x₀ qc) = e qc := by
  sorry

/-- **Deck transformations are biholomorphisms**: precomposition by a loop
class is an analytic diffeomorphism of the cover commuting with the
projection. -/
theorem exists_pathCoverDeck_diffeomorph (γ : Path.Homotopic.Quotient x₀ x₀) :
    ∃ e : PathCover x₀ ≃ₘ^ω⟮𝓘(ℂ), 𝓘(ℂ)⟯ PathCover x₀,
      ∀ pc, e pc = pathCoverDeck x₀ γ pc := by
  sorry

/-- **The deck action is transitive on fibers**: two path classes with the
same endpoint differ by precomposition with a loop class at the basepoint. -/
theorem pathCoverDeck_transitive (pc qc : PathCover x₀)
    (h : pathCoverProj x₀ pc = pathCoverProj x₀ qc) :
    ∃ γ : Path.Homotopic.Quotient x₀ x₀, pathCoverDeck x₀ γ pc = qc := by
  sorry

end RiemannDynamics
